version: "3"
services:
  stratum:
    image: stratum
    container_name: stratum
    environment:
      POOL_ADDRESS: eu.ss.btc.com
      POOL_PORT: 3333
      WORKER_NAME: EZIDTest01
      CALLBACK_URL: "https://mining.digitalppl.com/api/shares/save"
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - "3333:3333"
      - "4444:4444"
    volumes:
      - ./code:/stratum
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 300; docker restart stratum; done"]
    restart: unless-stopped
